openapi: 3.0.0
info:
  title: Staff&Taff
  description: Staff&Taff helps ob seekers and recruiters to find each other
  version: 0.1.9

servers:
  - url: http://localhost:8080/api/v1
    description: local server
  - url: https://production.app/api/v1
    description: production server

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
security:
  - cookieAuth: []

paths:
  /user:
    $ref: "./_swagger/paths/user.yaml#/paths/~1user"
  /forgot-password:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1forgot-password"
  /reset-password:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1reset-password"
  /register:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1register"
  /login:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1login"
  /logout:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1logout"
  /verify-email:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1email-verification"
  /industries:
    $ref: "./_swagger/paths/industries.yaml#/paths/~1industries"
  /industry/{industry}:
    $ref: "./_swagger/paths/industries.yaml#/paths/~1industry~1{industry}"
  /industry/store:
    $ref: "./_swagger/paths/industries.yaml#/paths/~1industry~1store"
  /industry/update/{industry}:
    $ref: "./_swagger/paths/industries.yaml#/paths/~1industry~1update~1{industry}"
  /industry/delete/{industry}:
    $ref: "./_swagger/paths/industries.yaml#/paths/~1industry~1delete~1{industry}"
  /positions:
    $ref: "./_swagger/paths/positions.yaml#/paths/~1positions"
  /position/{position}:
    $ref: "./_swagger/paths/positions.yaml#/paths/~1position~1{position}"
  /position/store:
    $ref: "./_swagger/paths/positions.yaml#/paths/~1position~1store"
  /position/update/{position}:
    $ref: "./_swagger/paths/positions.yaml#/paths/~1position~1update~1{position}"
  /position/delete/{position}:
    $ref: "./_swagger/paths/positions.yaml#/paths/~1position~1delete~1{position}"
  /user-intent:
    $ref: "./_swagger/paths/stripe.yaml#/paths/~1user-intent"
  /payment:
    $ref: "./_swagger/paths/stripe.yaml#/paths/~1payment"
  /faq:
    $ref: "./_swagger/paths/faq.yaml#/paths/~1faq"
  /faq/{category}:
    $ref: "./_swagger/paths/faq.yaml#/paths/~1faq~1{category}"
  /faq/create:
    $ref: "./_swagger/paths/faq.yaml#/paths/~1faq~1create"
  /faq/update/{id}:
    $ref: "./_swagger/paths/faq.yaml#/paths/~1faq~1update~1{id}"
  /faq/delete/{id}:
    $ref: "./_swagger/paths/faq.yaml#/paths/~1faq~1delete~1{id}"
  /blog:
    $ref: "./_swagger/paths/blog.yaml#/paths/~1blog"
  /blog/create:
    $ref: "./_swagger/paths/blog.yaml#/paths/~1blog~1create"
  /blog/{id}:
    $ref: "./_swagger/paths/blog.yaml#/paths/~1blog~1{id}"
  /blog/delete/{id}:
    $ref: "./_swagger/paths/blog.yaml#/paths/~1blog~1delete~1{id}"
  /category:
    $ref: "./_swagger/paths/categories.yaml#/paths/~1category"
  /category/create:
    $ref: "./_swagger/paths/categories.yaml#/paths/~1category~1create"
  /category/delete/{id}:
    $ref: "./_swagger/paths/categories.yaml#/paths/~1category~1delete~1{id}"
